server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/plazoleta
    username: root
  application.name: restaurant-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
appDescription: "Plaza de comidas"
appVersion: "1.0.0"
