server:
  port: 8083

spring:
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/cristhianPragma/plazoleta-de-comidas
          search-paths: config-data

  application:
    name: config-service

