server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usuarios_plazoleta
    username: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  jwt:
    secret: openb
    expiration-ms: 86400000


appDescription: "Plaza de comidas"
appVersion: "1.0.0"
